apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-kube2es-config
  namespace: default
data:
  fluent.conf: |-
    <source>
      @type tail
      format json
      time_key time
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%L%z
      keep_time_key true
      tag reform.*
      read_from_head true
    </source>

    <source>
      @type systemd
      tag kubelet
      path /var/log/journal
      filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
      read_from_head true
      pos_file /var/log/kubelet.journal.pos
    </source>

    <filter kubelet>
      @type systemd_entry
      field_map {"MESSAGE": "log"}
      field_map_strict true
    </filter>

    <match reform.**>
      @type record_reformer
      enable_ruby true
      tag kubernetes.${tag_suffix[4].split('-')[0..-2].join('-')}
      <record>
        @timestamp ${Time.parse(record["time"]).strftime("%Y-%m-%dT%H:%M:%S.%L%z")}
      </record>

      ## The record "time" has the nanosecond precision, but kibana insists on sorting the fields by millisecond
      ## so we need this to be able to debug same-millisecond messages
      time_nano ${"%10.9f" % Time.parse(record["time"])}
    </match>

    <filter kubernetes.*>
      @type parser
      format json
      key_name log
      reserve_data yes
      suppress_parse_error_log true
    </filter>

    <match kubernetes.fluentd-kube2es*>
      @type null
    </match>

    <match kubernetes.**>
      @type copy

      <store>
        @type stdout
        @id kubernetes_stdout
      </store>

      <store>
        @type elasticsearch
        host 172.16.0.19
        port 9200
        logstash_format true
        logstash_prefix kubernetes
        include_tag_key true
        flush_interval 10s
        reconnect_on_error true
        reload_connections false
        resurrect_after 5
      </store>

    </match>

    <match kubelet.**>
      @type copy

      <store>
        @type stdout
        @id kubelet_stdout
      </store>

      <store>
        @type elasticsearch
        host 172.16.0.19
        port 9200
        logstash_format true
        logstash_prefix kubelet
        include_tag_key true
        flush_interval 10s
        reconnect_on_error true
        reload_connections false
        resurrect_after 5
      </store>

    </match>

