apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-kube2es
spec:
  template:
    metadata:
      labels:
        name: fluentd-kube2es
    spec:
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 0.15
          image: eu.gcr.io/net4machines/fluentd-kube2es:3
          name: fluentd-kube2es
          volumeMounts:
            - name: docker
              mountPath: /var/lib/docker
            - name: log
              mountPath: /var/log
      volumes:
        - name: log
          hostPath:
              path: /var/log
        - name: docker
          hostPath:
              path: /var/lib/docker
